@startuml
entity Perfil {
	*id : uuid
	nome : text
	*criado_em : datetime
	*atualizado_em : datetime
}
entity Usuario {
	*id : uuid
	nome : text
	email : text
	login : text
	senha : text
	ultima_atualizacao_senha : datetime
	criado_em : datetime
	atualizado_em : datetime
}
entity PerfilUsuario {
	*perfil_id : uuid
	*usuario_id : uuid
	*data_hora_associacao : datetime
}
entity HistoricoPerfilUsuario {
	*id_historico_perfil_usuario : uuid
	*perfil_id : uuid
	*usuario_id : uuid
	*data_hora_associacao : datetime
	data_hora_desassociacao : datetime
}
entity RecursoSistema {
	*id : uuid
	nome_recurso : text
	detalhes : text
	criado_em : datetime
	atualizado_em : datetime
}
entity Permissao {
	*id : uuid
	perfil_id : uuid
	usuario_id : uuid
	recurso_id : uuid
	acesso_concedido : text
	data_hora_concessao : datetime
}
entity HistoricoConcessaoAcesso {
	*id : uuid
	permissao_id : uuid
	data_hora_concessao : datetime
	data_hora_revogacao : datetime
}
entity Pais {
	*id : uuid
	*nome : text
	sigla : text
	*criado_em : datetime
	*atualizado_em : datetime
}
entity Idioma {
	*id : uuid
	*nome : text
	sigla : text
	criado_em : datetime
}
entity IdiomaPais {
	*pais_id : uuid
	*idioma_id : uuid
	*criado_em : datetime
}

entity Tradutor {
	*id : uuid
	*idioma_id : uuid
	pais_id : uuid
	*nome : text
	*criado_em : datetime
}

Idioma ||--|{ Tradutor

entity Autor {
	*id : uuid
	*nome : text
	*criado_em : datetime
}

entity Versao {
	*id : uuid
	*tradutor_id : uuid
	*idioma_id : uuid
	pais_id : uuid
	*nome : text
	detalhes : text
	*fonte : text
	*criado_em : datetime
	*atualizado_em : datetime
}

Idioma ||--|{ Versao
Tradutor ||--|{ Versao
Pais ||--|{ Versao

entity LivroVersao {
	*livro_versao_id : uuid
	*livro_id : uuid
	*versao_id : uuid
	*fonte : text
	nome_versao : text
	detalhes : text
	*criado_em : datetime
	*atualizado_em : datetime
}
entity Livro {
	*id : uuid
	*nome : text
	autor_id : uuid
	ano_estimado_escrita : number
	idioma_original_id : uuid
	apocrifo : bool
	descricao : text
	detalhes : text
	parte_biblia : text
	*criado_em : datetime
	*atualizado_em : datetime
}

Autor ||--|{ Livro
Idioma ||--|{ Livro
LivroVersao }|--|{ Livro
Versao }|--|{ LivroVersao

entity Capitulo {
	*id : uuid
	livro_id : uuid
	numero : number
	apocrifo : bool
	detalhes : text
	*criado_em : datetime
}

Livro ||--|{ Capitulo

entity Versiculo {
	*id : uuid
	capitulo_id : uuid
	livro_versao_id : uuid
	idioma_id : uuid
	texto : text
	fonte : text
	*criado_em : datetime
	*atualizado_em : datetime
}

Capitulo ||--|{ Versiculo
Livro ||--|{ Versiculo
Versao ||--|{ Versiculo
Idioma ||--|{ Versiculo
@enduml